#!/usr/bin/env bash
# Weekly REPORT-ONLY sweep of B2 storage growth. Deletes nothing, ever.
#
# Why this exists
# ---------------
# `ckpt_retention.py` is the bucket-side retention tool and it is marked
# GOVERNING in README.md. Its own docstring opens with "nothing has ever removed
# any of it" — and as of the 2026-08-09 audit that was still literally true:
# there was no timer, no service and no fleetd hook that ran it. The box-side
# half of checkpoint lifecycle is automated; the bucket-side half was a tool
# somebody had to remember. The bucket doubled in five days while nobody looked.
#
# The same audit found the published inventory roll-up
# (upstream-bench/archive/manifests/b2/SUMMARY.md) understating the bucket by
# ~2x for the same reason: it is only ever regenerated by hand.
#
# So this script closes both, and does it WITHOUT taking a position on the
# standing "no B2 deletes" invariant (B2_EFFICIENCY_PLAN_2026-07-09.md:153).
# It re-indexes, it plans, it reports. Arming a real sweep is an owner ruling —
# see RETENTION_SWEEP.md.
#
#   tools/vast/retention_report.sh            # write a report, print the summary
#   tools/vast/retention_report.sh --quiet    # write it, print only if it grew
#
# Report goes to $HERDD_RETENTION_REPORTS, else <upstream-bench>/archive/reports/
# b2-growth/. NEVER ~/tmp: that default is exactly how data goes missing
# (upstream-bench/WHERE_IS_THE_DATA.md §5).
set -uo pipefail

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
QUIET=0
[[ "${1:-}" == "--quiet" ]] && QUIET=1

# Credentials live in the repo-root .env (workstation ops pair). Sourced, never
# echoed — `herdd show` output carries live secrets and so does this file.
if [[ -f "$REPO_ROOT/.env" ]]; then
  set -a; . "$REPO_ROOT/.env"; set +a
fi
: "${B2_BUCKET:=example-runs-bucket}"; export B2_BUCKET

# upstream-bench holds both the inventory tool and the report destination.
# Resolved through scripts/grind/bench_paths.py and NOT by a local
# `../upstream-bench` guess: that guess is wrong from any worktree under `out/`,
# which is where most work on this box actually happens. bench_paths' rule 5
# exists for exactly that case (it walks to the MAIN checkout first).
BENCH=$(python3 -c '
import sys; sys.path.insert(0, sys.argv[1] + "/scripts/grind")
import bench_paths; print(bench_paths.upstream_bench())' "$REPO_ROOT" 2>/dev/null)
if [[ -z "$BENCH" || ! -d "$BENCH/archive" ]]; then
  echo "retention_report: cannot locate upstream-bench." >&2
  echo "  set \$UPSTREAM_BENCH, or see scripts/grind/bench_paths.py for the" >&2
  echo "  five resolution rules and how to configure one." >&2
  exit 2
fi
OUT_DIR="${HERDD_RETENTION_REPORTS:-$BENCH/archive/reports/b2-growth}"
mkdir -p "$OUT_DIR"
STAMP=$(date -u +%Y-%m-%dT%H%MZ)
REPORT="$OUT_DIR/$STAMP.md"

# Both steps get a hard ceiling. Measured 2026-08-09: `ckpt_retention.py
# inventory` was killed by a 30-minute timeout having produced NO output — its
# rclone listing walks jobs/*/checkpoints/ and does not scale. A weekly timer that
# can wedge forever is worse than one that reports a timeout, so a timeout is a
# REPORTED OUTCOME here and not a silent failure.
INV_TIMEOUT="${HERDD_RETENTION_INV_TIMEOUT:-3600}"
PLAN_TIMEOUT="${HERDD_RETENTION_PLAN_TIMEOUT:-3600}"

{
  echo "# B2 growth report — $STAMP"
  echo
  echo "Report-only. This run deleted nothing and cannot: no code path here"
  echo "passes \`--apply\`. See \`tools/vast/RETENTION_SWEEP.md\`."
  echo
  echo '## Inventory'
  echo
  echo '```'
} > "$REPORT"

timeout "$INV_TIMEOUT" python3 "$BENCH/archive/b2_inventory.py" >> "$REPORT" 2>&1
INV_RC=$?
if [[ $INV_RC -eq 124 ]]; then
  echo "TIMED OUT after ${INV_TIMEOUT}s — inventory NOT refreshed this run" >> "$REPORT"
fi

{
  echo '```'
  echo
  echo '## Current roll-up'
  echo
} >> "$REPORT"
if [[ -f "$BENCH/archive/manifests/b2/SUMMARY.md" ]]; then
  sed -n '/^| prefix/,/^| \*\*total/p' "$BENCH/archive/manifests/b2/SUMMARY.md" >> "$REPORT"
fi

{
  echo
  echo '## Retention plan (DRY RUN — `ckpt_retention.py plan`)'
  echo
  echo 'Five gates, every unknown resolving to KEEP. This is what a sweep WOULD'
  echo 'do if one were armed; nothing here is executed.'
  echo
  echo '```'
} >> "$REPORT"

timeout "$PLAN_TIMEOUT" python3 "$REPO_ROOT/tools/vast/ckpt_retention.py" plan >> "$REPORT" 2>&1
PLAN_RC=$?
if [[ $PLAN_RC -eq 124 ]]; then
  echo "TIMED OUT after ${PLAN_TIMEOUT}s — no plan produced this run." >> "$REPORT"
  echo "(Known: the jobs/*/checkpoints/ listing does not scale. Not a credential" >> "$REPORT"
  echo " problem — recording it as a timeout rather than an error is deliberate.)" >> "$REPORT"
fi
echo '```' >> "$REPORT"

# The delta against the previous report is the whole point: a single size is a
# number, two sizes are a trend, and it was the TREND nobody had.
PREV=$(ls -1 "$OUT_DIR"/*.md 2>/dev/null | grep -v "$STAMP" | tail -1)
# b2_inventory.py writes the roll-up as: | **total** | **N** | **X.XX GiB** | |
CUR_GIB=$(sed -n 's/^| \*\*total\*\* | \*\*[0-9]*\*\* | \*\*\([0-9.]*\) GiB\*\*.*/\1/p' \
          "$BENCH/archive/manifests/b2/SUMMARY.md" 2>/dev/null | head -1)
{
  echo
  echo '## Delta'
  echo
  if [[ -n "$PREV" ]]; then
    PREV_GIB=$(sed -n 's/^total_gib: \([0-9.]*\)$/\1/p' "$PREV" | head -1)
    if [[ -n "$PREV_GIB" && -n "$CUR_GIB" ]]; then
      echo "previous ($(basename "$PREV" .md)): ${PREV_GIB} GiB"
      echo "now: ${CUR_GIB} GiB"
      awk -v a="$PREV_GIB" -v b="$CUR_GIB" 'BEGIN{printf "change: %+.2f GiB (%+.2f $/month at $6/TB-mo)\n", b-a, (b-a)*1.073741824*0.006}'
    else
      echo "previous report has no machine-readable total; no delta this run."
    fi
  else
    echo "no previous report — this is the baseline."
  fi
  echo
  echo "total_gib: ${CUR_GIB:-unknown}"
} >> "$REPORT"

if [[ $QUIET -eq 0 ]]; then
  echo "wrote $REPORT"
  tail -12 "$REPORT"
fi
exit 0
